# Generated by Django 4.2.5 on 2024-12-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aluno_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aluno',
            name='serie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
