# Generated by Django 4.2.5 on 2024-12-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_aluno_created_at_remove_aluno_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
