# Generated by Django 4.2.5 on 2024-12-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aluno_cpf_alter_aluno_nome_alter_aluno_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(max_length=10),
        ),
    ]
