# Generated by Django 4.2.5 on 2024-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_aluno_serie_alter_aluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
