# Generated by Django 4.2.5 on 2024-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_aluno_cpf_alter_aluno_nome_alter_aluno_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
