# Generated by Django 4.2.5 on 2024-12-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aluno_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
